# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
