# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='backend.Category'),
        ),
    ]
