# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
