# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170402_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Publish'), (3, 'Unpublish')], default=1),
        ),
    ]
