# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Unpublished')], default=1),
        ),
    ]
