# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='galleries',
            field=models.ManyToManyField(to='backend.Gallery'),
        ),
    ]
