# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170425_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default=None, upload_to='thumbs/%Y/%m/%d'),
        ),
    ]
