# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20170425_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
    ]
