# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='galleries',
        ),
        migrations.AddField(
            model_name='tip',
            name='photos',
            field=models.ManyToManyField(to='backend.Image'),
        ),
    ]
