# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20170506_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
