# Generated by Django 2.0.2 on 2018-03-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20180325_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='tip',
            name='tip_type',
            field=models.IntegerField(choices=[(1, 'Diet')], default=1),
        ),
    ]
